version: "3"

services:
    # Laravel Application
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    # Nginx Service
    nginx:
        image: nginx:stable-alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - app-network

    # PostgreSQL Service
    db:
        image: postgres:14
        container_name: laravel-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network

# Volumes
volumes:
    postgres_data:

# Networks
networks:
    app-network:
        driver: bridge
